/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 grabfigur.glb
Author: noe-3d.at (https://sketchfab.com/www.noe-3d.at)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/grabfigur-ed8966eacd2747adbaa86172f4b7c7eb
Title: Grabfigur
*/
// @ts-nocheck
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Statue(props) {
  const { nodes, materials } = useGLTF('assets/grabfigur.glb')
  return (
    <group {...props} dispose={null} rotation={[1.5, 0, 0]} position={[0, 0, 0]}>
      <group rotation={[-Math.PI / 2, 0, -1.53]} scale={0.1}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.Grabfigur_O_Material_u1_v1} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.Grabfigur_O_Material_u1_v1} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.Grabfigur_O_Material_u1_v1} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.Grabfigur_O_Material_u1_v1} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.Grabfigur_O_Material_u1_v1} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.Grabfigur_O_Material_u1_v1} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.bottom} />
      </group>
    </group>
  )
}

useGLTF.preload('/grabfigur.glb')
